#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  basic:
    external:
      name: network

services:
  cliSupervisors:
    container_name: cliSupervisors
    image: hyperledger/fabric-tools:2.0.0-beta
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.supervisors.put.poznan.pl:9051
      - CORE_PEER_LOCALMSPID=SupervisorsMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/supervisors.put.poznan.pl/users/Admin@supervisors.put.poznan.pl/msp
      - CORE_CHAINCODE_KEEPALIVE=10
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/supervisors.put.poznan.pl/peers/peer0.supervisors.put.poznan.pl/tls/ca.crt
      - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/put.poznan.pl/orderers/orderer.put.poznan.pl/msp/tlscacerts/tlsca.put.poznan.pl-cert.pem
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../../../../organization/supervisors:/opt/gopath/src/github.com/
        - ./../../../../../network/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
        - basic
