# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.put.poznan.pl:
  peer0.supervisors.put.poznan.pl:
  peer0.students.put.poznan.pl:

networks:
  thesis:

services:

  orderer.put.poznan.pl:
    container_name: orderer.put.poznan.pl
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../organizations/ordererOrganizations/put.poznan.pl/orderers/orderer.put.poznan.pl/msp:/var/hyperledger/orderer/msp
        - ../organizations/ordererOrganizations/put.poznan.pl/orderers/orderer.put.poznan.pl/tls/:/var/hyperledger/orderer/tls
        - orderer.put.poznan.pl:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - thesis

  peer0.supervisors.put.poznan.pl:
    container_name: peer0.supervisors.put.poznan.pl
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_thesis
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.supervisors.put.poznan.pl
      - CORE_PEER_ADDRESS=peer0.supervisors.put.poznan.pl:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.supervisors.put.poznan.pl:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.supervisors.put.poznan.pl:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.supervisors.put.poznan.pl:7051
      - CORE_PEER_LOCALMSPID=SupervisorsMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/supervisors.put.poznan.pl/peers/peer0.supervisors.put.poznan.pl/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/supervisors.put.poznan.pl/peers/peer0.supervisors.put.poznan.pl/tls:/etc/hyperledger/fabric/tls
        - peer0.supervisors.put.poznan.pl:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
    networks:
      - thesis

  peer0.students.put.poznan.pl:
    container_name: peer0.students.put.poznan.pl
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_thesis
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.students.put.poznan.pl
      - CORE_PEER_ADDRESS=peer0.students.put.poznan.pl:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.students.put.poznan.pl:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.students.put.poznan.pl:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.students.put.poznan.pl:9051
      - CORE_PEER_LOCALMSPID=StudentsMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/students.put.poznan.pl/peers/peer0.students.put.poznan.pl/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/students.put.poznan.pl/peers/peer0.students.put.poznan.pl/tls:/etc/hyperledger/fabric/tls
        - peer0.students.put.poznan.pl:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9051:9051
    networks:
      - thesis
